Стилизация главной страницы
htmlacademy-htmlcss/1563575-sedona-29 pull request #4
Opened 2020-09-22 19:39 UTC by dimsimon

2020-09-25 20:38 UTC, zavsievich requested changes

2020-09-25 20:38 UTC, zavsievich commented on index.html
>  			<ul>
а nav__list нам не нужен?)

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +				<p class="main__header--paragraph">Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон! </p>
мне кажется, main нельзя считать "блоком" в привычном БЭМ-понимании
main в данном случае -- это секционный тег для придания семантики

2020-09-25 20:38 UTC, zavsievich commented on index.html
>   		</section>
очень часто первые вводные и красивые секции называют hero

2020-09-25 20:38 UTC, zavsievich commented on index.html
>  	<section>
эту секцию лучше сделать отдельным блоком и дать ей класс что-то типа features

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +				<p class="main__header--paragraph">Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон! </p>
--modifier -- модификатор -- это когда один и то же элемент немного отличается внешне, а ты делаешь два совершенно разных элемента (заголовок и подзаголовок) через модификаторы, не надо так 😔

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +				<p class="main__header--paragraph">Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон! </p>
можно сделать 
features__title и features__description

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +		<section class="section">
ну и если весь этот блок мы называем features, то секции-причины могут быть features__item, к примеру
потому что толку от этих секций без оющей секции features нет

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +					<li class="section__list">
у списка и элемента списка должны быть разные классы, как так, ты сразу одни и те же стили будешь применять и для списка, и для айтема, непорядок

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +						<p class="list--text">Рекомендуем пожить в настоящем мотеле, всё как в кино!</p>
откуда взялся класс list, если его ни разу в коде не было?

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +			</section>
БЭМ сломался: блок box, окей, значит, его элемент может быть box__item, чтобы было очевидно
внутри могут быть
box__title, box__number, box__text
ну или  
box__item-title, box__item-number, box__item-text 
тут уже как хочешь

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +			<h3 class="text--subtitle class="heading"">красивая дорога</h3>
класс в классе 🧐

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +			<h3 class="text--subtitle class="heading"">красивая дорога</h3>
КЛАСС!

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +		<article class="article">
не надо называть секции по тегу -- лучше называть их в соответсвии с контентом: эту секцию можно назвать, к примеру, reserve
частые названия классов можно поискать тут:
https://github.com/yoksel/common-words

2020-09-25 20:38 UTC, zavsievich commented on index.html
>  				<p>
этим элементам тоже нужны классы)

2020-09-25 20:38 UTC, zavsievich commented on index.html
>  			<h3>Социальные сети</h3>
класс

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +				<li><a class="footer__link" href="#"><img src="https://via.placeholder.com/146x148">Твиттер</a></li>
для li тоже нужен класс

2020-09-25 20:38 UTC, zavsievich commented on index.html
> +				<li><a class="footer__link" href="#"><img src="https://via.placeholder.com/146x148">Твиттер</a></li>
и для картинки тоже

2020-09-29 08:01 UTC, zavsievich requested changes

2020-09-29 08:01 UTC, zavsievich commented on index.html
> +		</section>
то есть эту секцию можно просто назвать welcome

2020-09-29 08:01 UTC, zavsievich commented on index.html
>  <!DOCTYPE html>
к этой странице те же замечания, что и к предыдущей

2020-09-30 17:24 UTC, dimsimon commented on index.html
>   		</section>
Этот текст мне нужно будет скрыть

2020-10-04 13:56 UTC, zavsievich requested changes
Нужны небольшие правки, а в остальном всё хорошо, ещё немного работы надо для понимания БЭМа. И почитай про наследование в css подробнее

2020-10-04 13:56 UTC, zavsievich commented on css/style.css
> +  margin: 0 40px;
делать тень и отступ по краям не нужно -- это, наверное, для выделения дизайна сделано, можно удалить

2020-10-04 13:56 UTC, zavsievich commented on css/style.css
> +  box-shadow: 0px 5px 15px rgba(0, 1, 1, 0.2);
делать тень и отступ по краям не нужно -- это, наверное, для выделения дизайна сделано, можно удалить

2020-10-04 13:56 UTC, zavsievich commented on css/style.css
> +  text-transform: uppercase;
так ты говоришь, что ВЕСЬ текст на сайте будет написан большими буквами. тебе это точно нужно?)

2020-10-04 13:56 UTC, zavsievich commented on css/style.css
> +  text-align: center;
так ты говоришь, что ВЕСЬ текст на сайте будет отцентрирован. тебе это точно нужно?)

2020-10-04 13:56 UTC, zavsievich commented on css/style.css
> +}
так ты полностью удаляешь текст, а не делаешь его невидимым 
посмотреть по теме: 
https://htmlacademy.ru/blog/boost/frontend/short-12
советую переименовать везде класс hidden-text в visually-hidden и использовать паттерн, описанный в статье

2020-10-04 13:56 UTC, zavsievich commented on css/style.css
> +  background-color: var(--white);
он и так по умолчанию белый -- строка лишняя

2020-10-04 13:56 UTC, zavsievich commented on css/style.css
> +  background-color: var(--white);
он и так по умолчанию белый -- строка лишняя

2020-10-04 13:56 UTC, zavsievich commented on hotels.html
> +		</div>
это можно и нужно запихнуть в section

2020-10-04 13:56 UTC, zavsievich commented on hotels.html
> +								<h3 class="hotels-list__title">Amara Resort & Spa</h3>
вкладывать лучше ссылку в заголовок, а не заголовок в ссылку

2020-10-04 13:56 UTC, zavsievich commented on hotels.html
> +	<main class="hotels">
отсюда можно убрать класс, ведь в css тебе не надо стилизовать main

2020-10-04 13:56 UTC, zavsievich commented on hotels.html
> +		<section class="hotels-content">
тут можно сократить класс до hotels

2020-10-04 13:56 UTC, zavsievich commented on hotels.html
> +			<div class="sort">
тогда это у нас будет hotels__sort

2020-10-04 13:56 UTC, zavsievich commented on hotels.html
> +			<ul class="hotels-list">
а это будет hotels__list

2020-10-04 13:56 UTC, zavsievich commented on hotels.html
> +		<section class="contacts">
footer__contacts

2020-10-04 13:56 UTC, zavsievich commented on hotels.html
> +		<section class="social">
footer__social

2020-10-04 13:56 UTC, zavsievich commented on hotels.html
> +		<p class="footer-author">
footer__author

2020-10-04 13:56 UTC, zavsievich commented on hotels.html
> +		<nav class="nav">
header__nav

2020-10-04 13:56 UTC, zavsievich commented on index.html
> +		<section class="content">
название класса должно отражать то, о чём этот блок
content не передаёт ничего: весь твой сайт -- это контент
лучше назвать features, к примеру

2020-10-04 13:56 UTC, zavsievich commented on index.html
> +		<section class="features">
тут не говорится об особенностях седоны, а просто блок введения: обычно такие называют hero

2020-10-04 13:56 UTC, zavsievich commented on index.html
> +			<section class="element">
элемент чего? лучше 
features__item/features__element

2020-10-04 13:56 UTC, zavsievich commented on index.html
> +			<div class="element-box">
можно сделать features__row

2020-10-04 13:56 UTC, zavsievich commented on index.html
> +				<section class="element element-box__item">
а это features__box

2020-10-04 13:56 UTC, zavsievich commented on index.html
> +		<article class="form">
я был не прав: это лучше сделать тегом section, ведь нам описывали все причины, чтобы мы заинтересовались

2020-10-04 13:56 UTC, zavsievich commented on index.html
> +			<div class="botton-borm">
а вот это как раз article, потому что можно вытянуть отсюда и вставить на любое другое место любой другой страницы

2020-10-04 14:04 UTC, dimsimon commented on css/style.css
> +  text-transform: uppercase;
но на макете весь текст на сайте выделен большими буква. чтобы не прописывать это везде, можно же задать в боди.

2020-10-04 14:19 UTC, dimsimon commented on index.html
> +			<section class="element">
почему блок называем как блок+элемент?
не проще ли назвать его просто box или container?

2020-10-04 14:25 UTC, dimsimon commented on index.html
> +			<div class="element-box">
снова. почему мы блок называем как блок+элемент?
https://ru.bem.info/methodology/naming-convention/ здесь прописано, что если блок имеет составное название из 2х и более слов, то мы перечисляем эти названия через знак "-", а название элемента отделяем от названия блока через "__". не много не понимаю.

2020-10-04 14:45 UTC, dimsimon commented on css/style.css
> +  background-color: var(--white);
я задаю цвет body серый, как на макете, а весь оставшийся цвет я помещаю в header, main и footer.

2020-10-04 15:09 UTC, dimsimon commented on hotels.html
> +	<main class="hotels">
ранее ты говорил о том, что нужно вешать АБСОЛЮТНО на все элементы классы.

2020-10-04 15:25 UTC, dimsimon commented on css/style.css
> +  margin: 0 40px;
если это есть на макете, почему я не должен это отображать?

2020-10-10 15:55 UTC, closed without merging